export const FLASHCARDS_KEY = 'Flashcards:Storage'
export const NOTIFICATION_KEY = 'Flashcards:Notification'
export const ADD_DECK = 'ADD_DECK'
export const GET_DECKS = 'GET_DECKS'
export const ADD_CARD = 'ADD_CARD'
export const GET_DECK = 'GET_DECK'